#
#	Portions Copyright 2026 The Hollycast Authors
#
#	This file is part of Hollycast.
#
#     Hollycast is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 2 of the License, or
#     (at your option) any later version.
#
#     Hollycast is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with Hollycast.  If not, see <https://www.gnu.org/licenses/>.
#

[versions]
agp = "9.2.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
commonsLang3 = "3.12.0"
documentfile = "1.0.1"
httpclient5 = "5.0.3"
slf4jAndroid = "1.7.35"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "commonsLang3" }
documentfile = { module = "androidx.documentfile:documentfile", version.ref = "documentfile" }
httpclient5 = { module = "org.apache.httpcomponents.client5:httpclient5", version.ref = "httpclient5" }
slf4j-android = { module = "org.slf4j:slf4j-android", version.ref = "slf4jAndroid" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
